alias: "Light: Orchestrator"
description: ""
triggers:
  - entity_id:
      - binary_sensor.entryway_occupancy_sensor
      - binary_sensor.kitchen_presence_sensor
      - binary_sensor.presence_sensor
      - binary_sensor.bathroom_occupancy_sensor
      - binary_sensor.door_sensor_closet_door
    to: null
    trigger: state
    for:
      hours: 0
      minutes: 0
      seconds: 1
conditions: []
actions:
  - alias: Entryway
    if:
      - condition: state
        entity_id: binary_sensor.entryway_occupancy_sensor
        state: "on"
    then:
      - condition: numeric_state
        entity_id: sensor.kitchen_lux_sensor
        below: 5
        alias: Brightness
      - alias: False Flags
        condition: not
        conditions:
          - condition: state
            entity_id: vacuum.roborock_s8_pro_ultra
            state:
              - cleaning
              - returning
          - condition: state
            entity_id: sensor.bedroom_sleep_status
            state:
              - awake
              - limbo
      - action: light.turn_on
        target:
          entity_id:
            - light.entryway_ceiling_lights
            - light.entryway_wall_light_local
      - wait_for_trigger:
          - trigger: state
            entity_id: binary_sensor.entryway_occupancy_sensor
            to: "off"
            for:
              seconds: 30
      - action: light.turn_off
        target:
          entity_id:
            - light.entryway_ceiling_lights
            - light.entryway_wall_light_local
  - alias: Bathroom
    if:
      - condition: state
        entity_id: binary_sensor.bathroom_occupancy_sensor
        state: "on"
      - alias: False Flags
        condition: not
        conditions:
          - condition: state
            entity_id: vacuum.roborock_s8_pro_ultra
            state:
              - cleaning
              - returning
    then:
      - action: light.turn_on
        target:
          entity_id: light.bathroom_lights_local
        data:
          rgb_color:
            - 255
            - 152
            - 60
          brightness_pct: 100
      - repeat:
          while:
            - condition: state
              entity_id: light.bathroom_lights_local
              state: "on"
          sequence:
            - delay:
                hours: 0
                minutes: 5
                seconds: 0
                milliseconds: 0
            - if:
                - condition: state
                  entity_id: binary_sensor.bathroom_motion_sensor
                  state: "on"
              then:
                - delay: "00:05:00"
              else:
                - action: light.turn_off
                  target:
                    entity_id: light.bathroom_lights_local
                - stop: No motion, shutting down
  - alias: Livingroom
    if:
      - condition: state
        entity_id: binary_sensor.presence_sensor
        state: "on"
    then:
      - condition: numeric_state
        entity_id: sensor.livingroom_lux_sensor
        below: 5
        alias: Brightness
      - alias: False Flags
        condition: not
        conditions:
          - condition: state
            entity_id: vacuum.roborock_s8_pro_ultra
            state:
              - cleaning
              - returning
          - condition: state
            entity_id: climate.air_conditioner
            state:
              - cool
              - dry
              - fan_only
      - action: light.turn_on
        target:
          entity_id:
            - light.livingroom_celing_lights
            - light.livingroom_desktop_lighs
            - light.smart_light_local
            - light.livingroom_wall_local
          device_id: 53ee26d067383ebd0018b8cd0d46e304
      - wait_for_trigger:
          - trigger: state
            entity_id: binary_sensor.presence_sensor
            to: "off"
            for:
              seconds: 30
      - action: light.turn_off
        target:
          entity_id:
            - light.livingroom_celing_lights
            - light.livingroom_desktop_lighs
            - light.smart_light_local
            - light.livingroom_wall_local
          device_id: 53ee26d067383ebd0018b8cd0d46e304
    else:
      - condition: state
        entity_id: binary_sensor.presence_sensor
        state: "off"
      - alias: False Flags
        condition: not
        conditions:
          - condition: state
            entity_id: binary_sensor.gaming_sensor
            state:
              - "on"
          - condition: state
            entity_id: media_player.plexamp_hideaway
            state:
              - playing
      - action: light.turn_off
        target:
          entity_id:
            - light.livingroom_celing_lights
            - light.livingroom_desktop_lighs
            - light.smart_light_local
            - light.livingroom_wall_local
          device_id: 53ee26d067383ebd0018b8cd0d46e304
  - alias: Kitchen
    if:
      - condition: state
        entity_id: binary_sensor.kitchen_presence_sensor
        state: "on"
    then:
      - condition: numeric_state
        entity_id: sensor.kitchen_lux_sensor
        below: 5
        alias: Brightness
      - alias: False Flags
        condition: not
        conditions:
          - condition: state
            entity_id: vacuum.roborock_s8_pro_ultra
            state:
              - cleaning
              - returning
      - condition: state
        entity_id:
          - light.kitchen_ceiling_lights
          - light.kitchen_window_lights_local
        state: "off"
      - action: light.turn_on
        target:
          entity_id:
            - light.kitchen_ceiling_lights
            - light.kitchen_window_lights_local
        data: {}
      - wait_for_trigger:
          - trigger: state
            entity_id: binary_sensor.kitchen_presence_sensor
            to: "off"
            for:
              seconds: 30
      - condition: state
        entity_id:
          - light.kitchen_ceiling_lights
          - light.kitchen_window_lights_local
        state: "on"
      - action: light.turn_off
        target:
          entity_id:
            - light.kitchen_ceiling_lights
            - light.kitchen_window_lights_local
        data: {}
  - alias: Bedroom
    if: []
    then:
      - alias: Brightness
        condition: numeric_state
        entity_id: sensor.bedroom_illuminance
        below: 5
      - alias: False Flags
        condition: not
        conditions:
          - condition: state
            entity_id: vacuum.roborock_s8_pro_ultra
            state:
              - cleaning
              - returning
          - condition: state
            entity_id: sensor.bedroom_sleep_status
            state:
              - awake
    enabled: false
  - alias: Closet
    if:
      - condition: state
        entity_id: binary_sensor.door_sensor_closet_door
        state:
          - "on"
    then:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.closet
      - wait_for_trigger:
          - trigger: state
            entity_id:
              - binary_sensor.door_sensor_closet_door
            from:
              - "on"
              - "off"
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.closet
mode: parallel
max: 5
