alias: "Lights: Livingroom Lights"
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.presence_sensor
    to: null
conditions:
  - condition: numeric_state
    entity_id: sensor.livingroom_lux_sensor
    below: 5
    alias: Brightness
actions:
  - alias: There
    if:
      - condition: state
        entity_id: binary_sensor.presence_sensor
        state: "on"
      - condition: not
        conditions:
          - condition: state
            entity_id: vacuum.roborock_s8_pro_ultra
            state: cleaning
          - condition: template
            value_template: >-
              {{ states('climate.air_conditioner') in ['cool', 'dry',
              'fan_only'] }}
        alias: False Flags
    then:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - light.livingroom_celing_lights
            - light.livingroom_desktop_lighs
            - light.smart_light_local
            - light.livingroom_wall_local
      - wait_for_trigger:
          - trigger: state
            entity_id:
              - binary_sensor.presence_sensor
            to: "off"
            for:
              hours: 0
              minutes: 0
              seconds: 30
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
            - light.livingroom_celing_lights
            - light.livingroom_desktop_lighs
            - light.smart_light_local
            - light.livingroom_wall_local
  - alias: Not There
    if:
      - condition: state
        entity_id: binary_sensor.presence_sensor
        state: "off"
      - alias: False Flags
        condition: not
        conditions:
          - condition: state
            entity_id: binary_sensor.gaming_sensor
            state: "on"
    then:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
            - light.livingroom_celing_lights
            - light.livingroom_desktop_lighs
            - light.smart_light_local
            - light.livingroom_wall_local
mode: restart
