alias: "Auto-Update: Dynamic Roborock Off-Peak Time"
description: >
  Automatically selects the cheapest off-peak period and sets Roborock's
  off-peak  start and end times based on Nord Pool SE3 pricing when new data
  becomes available.
triggers:
  - entity_id: sensor.nord_pool_se3_last_updated
    trigger: state
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ states('sensor.nord_pool_se3_off_peak_1_average') | float <
                 states('sensor.nord_pool_se3_off_peak_2_average') | float }}
        sequence:
          - target:
              entity_id: time.roborock_s8_pro_ultra_off_peak_start
            data:
              time: >
                {{
                as_timestamp(states('sensor.nord_pool_se3_off_peak_1_time_from')) 
                   | timestamp_custom('%H:%M:%S', false) }}
            action: time.set_value
          - target:
              entity_id: time.roborock_s8_pro_ultra_off_peak_end
            data:
              time: >
                {{
                as_timestamp(states('sensor.nord_pool_se3_off_peak_1_time_until')) 
                   | timestamp_custom('%H:%M:%S', false) }}
            action: time.set_value
      - conditions:
          - condition: template
            value_template: |
              {{ states('sensor.nord_pool_se3_off_peak_2_average') | float <=
                 states('sensor.nord_pool_se3_off_peak_1_average') | float }}
        sequence:
          - target:
              entity_id: time.roborock_s8_pro_ultra_off_peak_start
            data:
              time: >
                {{
                as_timestamp(states('sensor.nord_pool_se3_off_peak_2_time_from')) 
                   | timestamp_custom('%H:%M:%S', false) }}
            action: time.set_value
          - target:
              entity_id: time.roborock_s8_pro_ultra_off_peak_end
            data:
              time: >
                {{
                as_timestamp(states('sensor.nord_pool_se3_off_peak_2_time_until')) 
                   | timestamp_custom('%H:%M:%S', false) }}
            action: time.set_value
mode: single
