alias: "Climate: Optimal Temperature Regulator"
description: >
  This automation ensures your home is always at the optimal temperature by
  intelligently adjusting the air conditioning system based on readings from
  temperature and weather forecasts.
trigger:
  - platform: time_pattern
    minutes: /5
action:
  - service: climate.set_temperature
    target:
      entity_id: climate.air_conditioner
    data_template:
      temperature: "{{ states('sensor.air_conditioner_target_difference') | round}}"
